server:
  port: 8888
  servlet.context-path: /ssq
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fenkutest?useUnicode=true&characterEncoding=utf8&userSSL=flase
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    url: jdbc:sqlserver://175.175.140.60:1433;DatabaseName=SHWY_KNOWLEDGE_DB_JH
#    username: test
#    password: Qwer1234
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml

#logging:
#  level:
#    com.springboot.springbootjpa: debug
#    xatu.zsl: debug
#    org.springfromework.web: info
#    org.hibernate: error
#  file: log\myspringboot.log